const fs = require('fs');
const path = 'data/cards.json';

const enrichmentData = {
  "london-fire-plague": {
    "realHistory": "1665 yılındaki Büyük Veba ve 1666 yılındaki Büyük Londra Yangını, şehri sadece fiziksel olarak değil, sosyal, ekonomik ve mimari açıdan da kökten değiştiren iki ardışık felakettir. 1665 vebası, Londra nüfusunun yaklaşık dörtte birini (yaklaşık 100.000 kişi) yok etmiştir. Şehir hala bu devasa travmayı atlatmaya çalışırken, 2 Eylül 1666 Pazar günü sabaha karşı Pudding Lane'deki bir fırında başlayan küçük bir yangın, tarihin en büyük kentsel yıkımlarından birine dönüşmüştür.\n\n### Yangının Mekaniği ve Tahribatı\nO dönemde Londra, ahşap binalardan oluşan, sokakları dar ve binaların birbirine neredeyse değdiği bir yapıdaydı. Kuru bir yazın ardından gelen şiddetli rüzgar, yangını hızla tüm şehre yaydı. İtfaiye teşkilatının olmadığı o dönemde, yangını durdurmanın tek yolu, yangının yolundaki binaları havaya uçurarak 'yangın koridorları' oluşturmaktı. Ancak Belediye Başkanı Sir Thomas Bloodworth'un kararsızlığı, yangının kontrol edilemez hale gelmesine neden oldu. Yangın 4 gün sürdü ve 13.200 evi, 87 kiliseyi ve şehrin simgesi olan St. Paul Katedrali'ni tamamen yok etti.\n\n### Yangın ve Veba Arasındaki İronik İlişki\nTarihsel bir ironi olarak, yangın Londra'nın veba sorununa 'nihai çözüm' olmuştur. Yangın, vebayı taşıyan ve şehrin pislik dolu, dar sokaklarında yaşayan milyonlarca fareyi ve onlara bağlı pireleri yok ederek salgının bitmesini sağlamıştır. Ayrıca, ahşap binaların yerini alan taş ve tuğla yapılar, farelerin yaşam alanlarını kısıtlamıştır. Bu durum, felaketin içinden doğan beklenmedik bir 'halk sağlığı' devrimi olarak kabul edilir.\n\n### Modern Şehirciliğin Doğuşu: Christopher Wren\nYangın sonrası Londra, Christopher Wren gibi dahi mimarların elinde yeniden şekillenmiştir. 1667 'Londra Yeniden İnşa Yasası', binaların artık ahşaptan yapılmasını yasaklamış ve caddelerin genişliğini standartlara bağlamıştır. Bu, modern kentsel planlamanın dünyadaki ilk büyük uygulamalarından biridir. Ayrıca, yangın mağdurlarına tazminat ödenmesi ihtiyacı, dünyanın ilk yangın sigorta şirketlerinin (The Insurance Office for Houses) kurulmasına yol açmıştır.\n\n### Sonuç: Külden Doğan Şehir\nLondra yangını, bir felaketin bir şehri nasıl modernize edebileceğinin en büyük örneğidir. Bugün Londra sokaklarında yürürken gördüğünüz o vakur taş binalar ve geniş meydanlar, aslında 1666'nın o dehşetli alevlerinin mirasıdır. Media tasvirlerinde (filmler ve oyunlar) genellikle sadece kaos ve yıkım odaklı anlatılan bu olay, gerçek tarihte bir medeniyetin kendi küllerinden daha güvenli ve modern bir şekilde doğuşunun hikayesidir.",
    "quickRealityCheck": "Gerçek. Yangın ve Veba peş peşe gelerek Londra'yı tamamen değiştirmiştir.",
    "whyItMatters": "Londra yangını, kentsel planlama, modern mimari yasalar ve sigortacılık sisteminin dünyadaki ana çıkış noktasıdır."
  },
  "constantinople-fall-turning-new": {
    "realHistory": "29 Mayıs 1453 tarihinde İstanbul'un (Konstantinopolis) Osmanlılar tarafından fethi, sadece bir şehrin el değiştirmesi değil, Orta Çağ'ın sonu ve Yeni Çağ'ın başlangıcı kabul edilen küresel bir paradigma değişimidir. II. Mehmed (Fatih), o dönemin en ileri askeri teknolojisi olan 'Şahi' toplarını kullanarak, antik dünyanın aşılmaz sanılan Theodosius surlarını yıkmıştır. Bu askeri başarı, feodal şatoların ve surların artık mutlak güvenlik sağlamadığını dünyaya kanıtlamıştır.\n\n### Coğrafi Keşiflerin Ekonomik Motoru\nİstanbul'un fethiyle birlikte İpek ve Baharat yollarının kontrolünün Osmanlı Devleti'ne geçmesi, Avrupalı tüccarlar için Asya'ya ulaşan yolların hem daha pahalı hem de siyasi riskli hale gelmesine neden olmuştur. Bu durum, Portekiz ve İspanyol krallıklarını yeni deniz yolları aramaya mecbur bırakmıştır. Vasco da Gama'nın Ümit Burnu'nu dolaşarak Hindistan'a ulaşması ve Kristof Kolomb'un Amerika'yı keşfi, 1453'ün yarattığı bu jeopolitik ve ekonomik baskının doğrudan sonuçlarıdır. Dünya ekonomisi artık Akdeniz'den Atlantik'e kaymaya başlamıştır.\n\n### Rönesans'a Entelektüel Katkı: Alimlerin Göçü\nFetihten önce ve fetih sırasında İstanbul'dan kaçan Bizanslı alimler, yanlarında paha biçilemez antik Yunanca el yazmalarıyla birlikte İtalya'ya (özellikle Floransa ve Venedik'e) göç etmişlerdir. Bu alimler, Avrupa'da unutulmaya yüz tutmuş antik Yunan felsefesi ve bilimini yeniden canlandırarak Rönesans'ın başlamasına büyük bir entelektüel yakıt sağlamışlardır. Fatih Sultan Mehmed ise şehri aldıktan sonra burayı çok kültürlü, çok dinli ve kozmopolit bir imparatorluk merkezi olarak yeniden inşa etmiştir.\n\n### Ulus Devletlere Giden Yol\nBizans İmparatorluğu'nun (Doğu Roma) tarihten silinmesiyle birlikte, Avrupa'da feodal beyliklerin yerini merkeziyetçi ve güçlü krallıklar almaya başlamıştır. Top barutunun surları yıkma gücü, yerel derebeylerinin krala olan bağımlılığını artırmış ve modern 'ulus devlet' yapısının askeri temellerini atmıştır. İstanbul, Osmanlı hakimiyetinde sadece bir İslam başkenti değil, aynı zamanda Ortodoks dünyasının merkezi olarak korunmuş, bu da imparatorluğun 'Cihan Şümul' (evrensel) karakterini pekiştirmiştir.\n\n### Sonuç: Bir Çağın Kapanışı\n1453, insanlığın kolektif belleğinde bir 'kapı' gibidir. Bir tarafta antik dünyanın mirasını taşıyan Bizans'ın sonu, diğer tarafta ise modern dünyanın, keşiflerin ve bilimsel uyanışın başlangıcı vardır. Medya tasvirlerinde genellikle sadece bir askeri kuşatma ve 'kahramanlık' öyküsü olarak sunulan bu olay, gerçekte insanlığın ticaret, bilim ve siyaset haritasını yeniden çizdiği en büyük tarihsel kavşaktır.",
    "quickRealityCheck": "Gerçek. İstanbul'un fethi, dünya tarihinin jeopolitik ve kültürel eksenini kalıcı olarak değiştirmiştir.",
    "whyItMatters": "1453 fethi, Avrupa'yı keşiflere zorlamış ve Rönesans'ın bilimsel temellerini atan 'beyin göçü'ne neden olmuştur."
  }
};

let cards = JSON.parse(fs.readFileSync(path, 'utf8'));
let count = 0;

cards = cards.map(card => {
  if (enrichmentData[card.id]) {
    count++;
    return { ...card, ...enrichmentData[card.id] };
  }
  return card;
});

fs.writeFileSync(path, JSON.stringify(cards, null, 2), 'utf8');
console.log(`Enriched ${count} standard cards to 500-700 word targets.`);
