const fs = require('fs');
const path = 'data/cards.json';

const extraParagraphs = {
  "last-emperor-court-ritual": "\n\n### Yasak Şehir'in Sembolik Renkleri ve Feng Shui\nYasak Şehir'in mimarisi, Feng Shui prensiplerine ve Çin kozmolojisine göre titizlikle tasarlanmıştır. Şehrin kuzeyi, soğuk ve kötü ruhların geldiği yön olarak kabul edildiği için surlar bu yönde daha kalın ve yüksektir. Binaların çatıları, imparatorluk otoritesini simgeleyen parlak sarı kiremitlerle kaplıyken, sadece kütüphanenin çatısı yangına karşı koruma sağlaması için 'su' elementini simgeleyen siyah renktedir. Her bir kapıdaki çivilerin sayısı bile imparatorluk hiyerarşisine göre belirlenmişti. Bu fiziksel detaylar, imparatorun evrenin merkezindeki sarsılmaz yerini her gün yeniden hatırlatıyordu.\n\n### Mançukuo'da Bir Kukla: Bir Hayalin Sonu\nPu Yi'nin Mançukuo macerası, aslında bir imparatorluk hayalinin nasıl bir işgal aracına dönüştüğünün en acı örneğidir. Japonlar, onu 'Mançurya İmparatoru' olarak tahta çıkardıklarında, aslında bölgedeki direnişi kırmak ve sömürgeci faaliyetlerine meşruiyet kazandırmak istiyorlardı. Pu Yi, sarayında lüks içinde yaşarken, dışarıda birim 731 gibi dehşet verici askeri deneyler ve sistematik sömürü devam ediyordu. Pu Yi, bu vahşeti görmezden gelmeyi seçmiş veya buna zorlanmıştır. Bu sessizlik, onun tarihsel mirasına sürülen en büyük lekedir. O, sadece kendi sarayının değil, aynı zamanda Japon yayılmacılığının da tutsağıydı.",
  "crown-monarchy-symbol": "\n\n### BBC ve Monarşi: Modern Bir Ortaklık\nMonarşinin modern çağdaki sesi BBC olmuştur. Kraliçe'nin ilk kez 1957'de televizyondan yaptığı Noel konuşması, devlet kurumu olan BBC ile monarşi arasındaki o kopmaz bağın başlangıcıdır. BBC, monarşiyi bir 'ulusal hazine' olarak sunarken, monarşi de BBC'ye prestij ve 'İngilizlik' kimliği sağlamıştır. Bu medya ortaklığı, monarşinin en zor dönemlerinde bile halkla bağını koparmamasını sağlayan en güçlü araçtır. Bugün 'The Crown' gibi dizilerin küresel başarısı, aslında bu uzun süreli medya stratejisinin bir meyvesidir.\n\n### Kraliyet Ailesi ve Hayırseverlik Ekonomisi\nMonarşinin modern dünyadaki en somut meşruiyet kaynağı, kraliyet ailesinin desteklediği binlerce hayır kurumudur. Kraliçe ve ailesi, 3000'den fazla organizasyonun hamiliğini yürüterek, yılda milyarlarca poundluk bağış toplanmasına aracılık etmektedirler. Bu 'hayırseverlik' rolü, monarşiyi sadece bir sembol değil, aynı zamanda toplumsal fayda üreten aktif bir aktör haline getirir. İnsanlar, siyasetçilerin yapamadığı o birleştirici sosyal projeleri monarşinin liderliğinde görmekten mutluluk duyarlar. Bu durum, Tacın halkın kalbindeki yerini koruyan en önemli pratik güçtür.",
  "ac-syndicate-london": "\n\n### Londra Sisi ve Halk Sağlığı Krizi\n19. yüzyıl Londra'sının o meşhur 'sisi', aslında kömür dumanı ve sanayi atıklarının birleşimiyle oluşan ölümcül bir smog tabakasıydı. 1873 ve 1880 yıllarındaki büyük sis vakalarında binlerce insan solunum yolu hastalıklarından hayatını kaybetmiştir. Bu çevre felaketi, Londra'yı dünyanın ilk 'ekolojik kriz' metropolü haline getirmiştir. Şehir yönetimi, bu kirlilikle başa çıkmak için parklar kurmaya ve fabrikaları şehir dışına taşımaya başlamıştır. Oyundaki o gri ve dumanlı atmosfer, sadece estetik bir tercih değil, o dönemin acı bir fiziksel gerçeğidir.\n\n### Viktorya Döneminde İletişim: Posta ve Telgraf\nLondra bu dönemde dünyanın iletişim merkeziydi. 'Penny Black' ile başlayan ucuz posta sistemi, okuryazarlığın ve iletişimin halk tabanına yayılmasını sağlamıştır. Telgraf hatları ise Londra'yı New York, Bombay ve Sidney gibi uzak şehirlerle anlık olarak bağlamaya başlamıştı. Bilginin bu kadar hızlı akması, borsa spekülasyonlarını ve küresel ticareti tetiklemiştir. Londra, artık sadece bir liman değil, dünyanın ilk 'veri merkezi' haline gelmişti. Telgraf direkleri, o dönemin gökdelenleri gibi şehrin her yerinde yükseliyordu.",
  "mafia-prohibition": "\n\n### Yasak Döneminde Kadınların Rolü: Flappers ve İsyan\nAlkol yasağı, ironik bir şekilde kadınların kamusal alandaki özgürlüklerini artırmıştır. Eskiden kadınların girmesinin yasak olduğu barların yerini alan Speakeasies, kadın ve erkeğin bir arada eğlendiği ilk mekanlar olmuştur. 'Flapper' adı verilen yeni nesil kadınlar, kısa saçları, sigaraları ve içkileriyle geleneksel toplumsal normlara meydan okumuşlardır. Bu sosyal devrim, 1920'lerin o isyankar ruhunun ve ardından gelen kadın hakları hareketlerinin en önemli yakıtıdır. Yasak, sadece içkiyi değil, eski ahlaki kuralları da yeraltına itmiştir.\n\n### Alkolün Kimyasal Savaşı: Endüstriyel Zehirleme\nHükümet, içki üretimini durdurmak için endüstriyel alkollerin içine öldürücü dozda metil alkol ve gazyağı katılması talimatını vermiştir. Bu 'denatüre' alkolleri içen binlerce göçmen ve yoksul insan hayatını kaybetmiş veya kör olmuştur. Mafya, bu zehirli alkolü 'temizlemek' için kendi kimyagerlerini çalıştırmış ve sahte içki üretimini bir bilim dalına dönüştürmüştür. Bu durum, devletin kendi vatandaşına karşı yürüttüğü gizli ve kanlı bir savaşa dönüşmüştür. Prohibition, sadece bir yasak değil, insan hayatı üzerinden yapılan tehlikeli bir kumardır.",
  "band-of-brothers-airborne": "\n\n### Airborne Ekipmanları: Bir Paraşütçünün Yükü\nBir Easy Bölüğü askeri, atlayış sırasında yaklaşık 40-50 kilo ağırlığında ekipman taşıyordu. Bu yük; tüfek, mühimmat, el bombaları, K-rasyonları, yedek paraşüt, su matarası ve bazen bir makineli tüfek parçasından oluşuyordu. Bu kadar ağırlıkla karanlıkta yere inmek, her atlayışta bacak kırılması veya yaralanma riskini beraberinde getiriyordu. Paraşütçüler, inişten sonra bu ağır ekipmanlarla kilometrelerce yürümek ve hemen savaşa girmek zorundaydılar. Bu fiziksel dayanıklılık, hava indirme birliklerini diğer piyade birimlerinden ayıran en büyük özellikti.\n\n### Savaş Sonrası Hayat ve Currahee Mirası\nSavaştan dönen Easy Bölüğü gazileri, kurdukları o 'kardeşlik' bağını hayatları boyunca korudular. Her yıl düzenlenen birlik toplantıları, onların paylaştığı o travmatik ama kutsal bağın bir kutlamasıydı. Birçoğu sivil hayatta başarılı iş insanları, öğretmenler veya çiftçiler oldu; ancak kendilerini her zaman '101. Hava İndirme'nin bir parçası olarak tanımladılar. Currahee dağı, onların hayatındaki en büyük engeli ve zaferi simgeliyordu. Bu miras, bugün hala ABD ordusundaki hava indirme birlikleri için en büyük motivasyon kaynağı ve askeri etik referansıdır.",
  "lanoire-postwar-trauma": "\n\n### Los Angeles'ta Suç ve Medya: Magazinleşen Cinayetler\n1940'ların sonu, Los Angeles'ta 'sarı basın' (yellow journalism) döneminin zirvesidir. Gazeteler, cinayet mahallerine polisten önce gidiyor, delilleri karıştırıyor ve kurbanların özel hayatlarını manşetlere taşıyordu. Suç, halk için bir nevi eğlence ve dedikodu malzemesi haline gelmişti. Bu medya baskısı, LAPD üzerinde davaları hızlıca (ve bazen yanlış kişilerle) kapatma baskısı yaratıyordu. Cole Phelps'in davaları çözerken karşılaştığı o aceleci ve yozlaşmış ortam, medyanın yarattığı bu 'suç sirkinden' besleniyordu. Gerçek adalet, manşetlerin arasında kaybolup gidiyordu.\n\n### Savaş Sonrası Ekonomik Dönüşüm ve İşsizlik\nSavaş endüstrisinin aniden durmasıyla Los Angeles'ta binlerce işçi işsiz kalmış ve ekonomik bir durgunluk başlamıştır. Bu ekonomik belirsizlik, suç oranlarının artmasındaki en büyük etkendir. Eski askerlerin birçoğu, orduda öğrendikleri 'öldürme ve hayatta kalma' becerilerini sivil suç dünyasında kullanmaya başlamışlardır. Şehir, dışarıdan bakıldığında parıltılı bir Hollywood filmi gibi görünse de, içeride geçim derdi ve toplumsal öfke kaynıyordu. LA Noire, bu ekonomik çöküşün yarattığı o karanlık ve umutsuz havayı her ara sokakta hissettirir.",
  "shogun-trade-sakoku": "\n\n### Dejima'da Günlük Hayat: Bir Kültürel Karantina\nDejima adasındaki Hollandalı tüccarlar, bir nevi 'altın kafeste' yaşıyorlardı. Adadan ayrılmaları yasaktı ve Japon halkıyla temasları çok sınırlıydı. Ancak Hollandalıların getirdiği her yeni nesne (teleskoplar, saatler, tıbbi aletler), Japon aydınları arasında büyük bir heyecan yaratıyordu. 'Oranda-shumi' (Hollanda tutkusu) adı verilen bu merak, Japonya'nın geleneksel kalıplarını içeriden kırmaya başlamıştı. Dejima, sadece bir ticaret noktası değil, aynı zamanda fikirlerin sızdığı bir çatlaktı. Hollandalılar, her yıl Edo'ya giderek şoguna saygılarını sunmak ve dünya hakkında bilgi vermek zorundaydılar.\n\n### Sakoku ve Denizcilik Yasağı: Kıyı Savunması\nSakoku sadece insanların giriş-çıkışını değil, aynı zamanda büyük gemilerin inşasını da yasaklamıştı. Japonlar sadece kıyı ticaretine uygun küçük tekneler yapabiliyorlardı; bu, bir Japon'un denizaşırı bir ülkeye kaçmasını teknik olarak imkansız kılıyordu. Bu yasak, Japonya'nın denizcilik teknolojisinde bir süreliğine geri kalmasına neden olsa da, iç sularda devasa bir deniz taşımacılığı ağının gelişmesini sağlamıştır. Sahil kasabaları, bu iç ticaret sayesinde zenginleşmiş ve Japonya'nın yerel ekonomisinin bel kemiği haline gelmiştir. Bu 'içe dönük' denizcilik, Japonya'nın ada devleti karakterini pekiştirmiştir.",
  "ryan-higgins-boats": "\n\n### Pasifik Cephesinde Mercan ve Çelik Yarışı\nPasifik Savaşı'nda Higgins Botları, sadece kumlara değil, keskin mercan resiflerine karşı da test edilmiştir. Botların sığ su tasarımı, askerlerin gemilerden kıyıya güvenle geçmesini sağlıyordu. Ancak Tarawa gibi bazı savaşlarda, botların mercanlara takılması büyük trajedilere yol açmıştır. Bu durum, botların sürekli geliştirilmesine ve amfibi harekat planlarının daha detaylı yapılmasına neden olmuştur. Higgins, botlarını savaşın ihtiyaçlarına göre her ay yeniden optimize ediyordu. Pasifik'in her adası, bu botların dayanıklılığının ve müttefik lojistiğinin birer sınav sahası olmuştur.\n\n### Kadınların Higgins Fabrikalarındaki Emeği\nNew Orleans'taki Higgins fabrikalarında çalışanların büyük çoğunluğunu kadınlar oluşturuyordu. 'Rosie the Riveter' imajının gerçek hayattaki karşılığı olan bu kadınlar, binlerce botu rekor sürelerde inşa ettiler. Onların titizliği ve üretim hızı, Amerika'nın 'üretim mucizesi'nin en önemli parçasıydı. Kadınlar, sadece bot üretmekle kalmamış, aynı zamanda savaş sonrası Amerikan iş gücü piyasasının kalıcı bir parçası haline gelmişlerdir. Higgins, fabrikalarındaki bu çeşitliliği her zaman bir gurur kaynağı olarak görmüş ve başarısını bu 'görünmez orduya' borçlu olduğunu söylemiştir.",
  "last-kingdom-danelaw": "\n\n### Danelaw'da Toprak ve Mülkiyet Rejimi\nDanelaw bölgesinde toprak mülkiyeti, Anglo-Sakson bölgelerine göre çok daha dinamik ve serbestti. Vikingler, 'Carucate' adı verilen yeni bir arazi ölçüm birimi getirmişlerdi; bu, sekiz öküzden oluşan bir takımın bir yılda sürebileceği arazi miktarını temsil ediyordu. Bu pratik yaklaşım, tarımsal verimliliği artırmış ve köylülerin toprak sahibi olmasını kolaylaştırmıştır. Mülkiyet kavgaları yerel 'Thing' meclislerinde çözülüyor ve kararlar taşlara kazınarak kalıcı hale getiriliyordu. Bu hukuki netlik, Danelaw'ın ekonomik başarısının ve yerel halkın Viking yönetimine olan uyumunun asıl sebebidir.\n\n### Vikinglerin İngiliz Aksanındaki İzleri\nBugün Kuzey İngiltere ve İskoçya'daki yerel ağızlarda duyulan sert ve gırtlaksı tınılar, doğrudan Danelaw döneminden kalma İskandinav etkisidir. 'Kirk' (Kilise), 'Bairn' (Çocuk) gibi kelimeler hala bu bölgelerde günlük dilde yaşamaktadır. Danelaw, sadece bir toprak parçası değil, İngiliz dilinin içine işlemiş bir ses hafızasıdır. Bu dilsel miras, İngiltere'nin kuzey ve güney arasındaki o meşhur kültürel bölünmenin de tarihsel kökenlerinden birini oluşturur. Vikinglerin dilleri, fethettikleri topraklarda kılıçlarından çok daha kalıcı izler bırakmıştır."
};

let cards = JSON.parse(fs.readFileSync(path, 'utf8'));
cards = cards.map(card => {
  if (extraParagraphs[card.id]) {
    card.realHistory += extraParagraphs[card.id];
  }
  return card;
});

fs.writeFileSync(path, JSON.stringify(cards, null, 2), 'utf8');
console.log('Final nudge applied. All target flagships updated.');
