const fs = require('fs');
const path = 'data/cards.json';

const megaDeepContent = `1274 ve 1281 yıllarındaki Moğol istilaları, Japonya'nın dış bir güç tarafından fethedilmeye en çok yaklaştığı, ulusal kimliğin ve askeri doktrinin kökten sarsıldığı devasa tarihsel kırılma noktalarıdır. Kubilay Han önderliğindeki Moğol İmparatorluğu, Çin ve Kore'yi fethettikten sonra gözünü 'Doğu'daki Altın Adalar'a dikmişti. Bu istila girişimi, sadece iki ordunun çarpışması değil, aynı zamanda kıtasal bir imparatorluğun teknolojik ve disiplinli savaş makinesi ile bir ada devletinin bireysel onura dayalı feodal savaşçı sınıfının (samuraylar) kaçınılmaz çatışmasıydı.

### İstila Öncesi Diplomatik Kriz ve Moğol Stratejisi
Moğol istilası bir gecede başlamadı. Kubilay Han, 1266 yılından itibaren Japonya'ya bir dizi elçi göndererek 'Hakkaniyetli bir haraç ve sadakat' talep etti. Ancak o dönemde Japonya'yı fiilen yöneten Kamakura Şogunluğu'nun genç naibi Hojo Tokimune, bu talepleri sadece reddetmekle kalmadı, elçilerin bir kısmını idam ettirerek geri dönüşü olmayan bir savaşın fitilini ateşledi. Moğollar, Japonya'ya saldırmak için o dönemin en gelişmiş donanmasını inşa ettiler. Koreli gemi ustaları tarafından yapılan yaklaşık 900 gemilik devasa filo, sadece asker değil, aynı zamanda atlar, kuşatma silahları ve barutlu patlayıcılar taşıyordu. Bu lojistik güç, Japonya'nın daha önce hiç karşılaşmadığı bir ölçekteydi. Moğol stratejisi, Tsushima ve Iki adalarını ele geçirerek ana karaya yapılacak büyük saldırı için güvenli bir ikmal hattı oluşturmaktı.

### Komoda Sahili Muharebesi: İlk Kan ve Savunmasız Adalar
1274 yılının Ekim ayında Moğol filosu Tsushima adasına ulaştı. Ghost of Tsushima oyununda Jin Sakai'nin ailesinin yok oluşuyla dramatize edilen bu an, tarihsel olarak Tsushima Valisi So Sukekuni ve onun 80 sadık samurayının binlerce Moğol askerine karşı imkansız direnişidir. Samuraylar, o dönemin geleneği olan 'bire bir onurlu düello' (Ikki-uchi) için isimlerini bağırarak ileri atıldıklarında, Moğollar bu durumu anlam veremeyerek toplu okçu mangalarıyla karşılık verdiler. Sukekuni ve adamları, sayıca üstünlük ve yabancı savaş taktikleri karşısında tamamen yok edildiler. Bu katliam, Japon askeri sınıfına 'eski kuralların artık geçerli olmadığını' gösteren ilk acı dersti. Moğollar ardından Iki adasına geçmiş ve orada da benzer bir yıkım gerçekleştirmişlerdir.

### Teknolojik Şok: Barutlu Bombalar (Tetsuhau) ve Kimyasal Silahlar
Japonların istila sırasında yaşadığı en büyük teknolojik şok, Moğolların kullandığı barutlu bombalardı. Çinli mühendisler tarafından geliştirilen ve 'Tetsuhau' adı verilen bu seramik veya metal kaplı bombalar, hem patlama etkisiyle doğrudan zarar veriyor hem de çıkardığı dehşetli gürültüyle Japon atlarını ürküterek samuray süvarilerini işlevsiz bırakıyordu. Japonlar o güne kadar barutu sadece havai fişek veya tıbbi amaçlarla tanıyorlardı; bir silah olarak kullanımı karşısında tamamen çaresiz kaldılar. Ayrıca Moğolların kullandığı zehirli oklar ve ateşli mızraklar, Japonların 'adil savaş' anlayışını temelinden sarsmıştır. Arkeolojik kazılarda Takashima adası açıklarında bulunan patlamamış Tetsuhau örnekleri, bu silahların o dönemdeki gelişmişliğini kanıtlamaktadır.

### Samuray Doktrininin Evrimi ve Katana'nın Doğuşu
Moğol istilası, Japon kılıç yapım sanatını da sonsuza dek değiştirmiştir. O dönemin ana kılıcı olan 'Tachi', daha ince ve zarifti; ancak Moğolların deri ve metal karışımlı kalın zırhlarına çarptığında sık sık kırılıyor veya körleşiyordu. Efsanevi kılıç ustası Masamune'nin de dahil olduğu bir ekol, bu başarısızlıktan ders çıkararak daha dayanıklı, kavisli ve sert çelikten üretilen 'Katana' formunu mükemmelleştirmiştir. Ayrıca samuraylar, atlı okçuluktan ziyade yaya olarak, grup disiplini içinde savaşmayı ve pusu kurmayı öğrenmek zorunda kaldılar. Oyunun ana teması olan 'Hayalet' (Ghost) taktikleri, aslında bu tarihsel 'eski onurlu yoldan, hayatta kalmayı sağlayan yeni yola' geçişin bir temsilidir. Samuraylar artık sadece düello yapmıyor, düşmanın lojistik hatlarını hedef alan yıpratma savaşları yürütüyorlardı.

### Kamikaze: İlahi Rüzgar ve Tayfunların Etkisi
Japonya'yı Moğol boyunduruğundan kurtaran asıl güç, askeri başarıdan ziyade doğanın kendisiydi. 1274'teki ilk istila girişimi sırasında, Moğol donanması kıyıda geceleme hatasına düşmüş ve aniden çıkan bir fırtına gemilerin çoğunu birbirine çarparak batırmıştır. 1281'deki ikinci ve çok daha büyük istila girişiminde ise (bu sefer yaklaşık 140.000 askerle gelmişlerdi), Japonların sahillere inşa ettiği devasa savunma duvarları (Genko Borui) Moğolları kıyıda tutmuş ve ardından gelen 'Büyük Tayfun' Moğol donanmasını neredeyse tamamen yok etmiştir. Japon halkı bu fırtınalara 'Kamikaze' (Tanrıların Rüzgarı) adını vermiş ve bu olay Japonya'nın 'tanrılar tarafından korunan kutsal topraklar' olduğu inancını asırlarca pekiştirmiştir. Bu inanç, II. Dünya Savaşı'ndaki intihar pilotlarına isim babalığı yapacak kadar derinleşmiştir.

### Arkeolojik Kanıtlar ve Batık Filo
Modern deniz arkeolojisi, Moğol istilalarının boyutlarını doğrulamaktadır. Takashima adası sularında yapılan araştırmalar, Moğol gemilerinin kalıntılarını, askerlerin kullandığı miğferleri, kılıçları ve hatta mühürleri gün ışığına çıkarmıştır. Bulunan gemi parçaları, aceleyle ve bazen kalitesiz malzemeyle yapıldıklarını göstermektedir; bu da Kubilay Han'ın Japonya'yı fethetmek için Koreli gemi yapımcılarına uyguladığı aşırı baskının bir sonucudur. Gemi tasarımlarındaki bu zafiyetler, tayfunlar karşısındaki mutlak yıkımın da teknik nedenlerinden biriydi.

### İstilanın Sosyo-Ekonomik ve Siyasi Mirası
Moğol savaşlarının Japonya üzerindeki etkisi sadece askeri değildi. Şogunluk, işgalcilere karşı savaşan samuraylara geleneksel olarak ganimet veya toprak dağıtamadı (çünkü düşman yenilmiş ama arkasında toprak bırakmamıştı). Bu durum, savaşa girmek için borçlanan samuray sınıfları arasında büyük bir hoşnutsuzluk yaratmış ve Kamakura Şogunluğu'nun otoritesinin sarsılmasına, sonunda da çökmesine yol açmıştır. Ayrıca istila korkusu, Japonya'yı dış dünyaya karşı daha savunmacı ve 'izolasyonist' bir zihniyete itmiştir. Tsushima adası, bu süreçten sonra hem Kore ile ticaretin kapısı hem de dış tehditlere karşı bir ileri karakol olarak stratejik önemini bin kat artırmıştır.

### Sonuç ve Kültürel Etki
Bugün Tsushima'daki Komoda sahili, üzerinde samurayların ve Moğolların anıtlarının bulunduğu hüzünlü ve vakur bir tarih parkı olarak bu devasa çarpışmayı hatırlatmaya devam etmektedir. Ghost of Tsushima oyunu, bu tarihsel olayları bir kurgu üzerinden anlatsa da, Japon halkının o dönemde yaşadığı dehşeti, fedakarlığı ve 'değişen dünyaya uyum sağlama' zorunluluğunu küresel bir kitleye ulaştırmayı başarmıştır. Moğol istilaları, Japonya'nın 'ada psikolojisini' ve dış güçlere karşı olan dirençli karakterini şekillendiren en önemli antik olaylardan biri olarak tarihteki yerini korumaktadır.`;

let cards = JSON.parse(fs.readFileSync(path, 'utf8'));
const cardIndex = cards.findIndex(c => c.id === 'ghost-tsushima-invasion');
if (cardIndex !== -1) {
  cards[cardIndex].realHistory = megaDeepContent;
  fs.writeFileSync(path, JSON.stringify(cards, null, 2), 'utf8');
  console.log('Enriched ghost-tsushima-invasion to true MEGA-deep levels (Targeting 900+ words).');
}
