const fs = require('fs');
const path = 'data/cards.json';

const enrichmentData = {
  "ac-origins-siwa": {
    "realHistory": "Ptolemaios dönemi Mısır'ı (M.Ö. 305 - M.Ö. 30), antik tarihin en büyüleyici ve karmaşık hibrit medeniyetlerinden biridir. Büyük İskender'in dünyayı fethetme rüyasının bir parçası olarak Mısır'a girişi, binlerce yıllık firavunluk düzenini sona erdirmemiş, aksine onu Yunan (Hellenistik) kültürüyle sentezlemiştir. İskender'in generallerinden Ptolemaios Soter tarafından kurulan hanedan, kendilerini Mısır halkına 'yabancı fatihler' olarak değil, 'yeni firavunlar' olarak sunmuştur. Bu meşruiyet arayışının kalbinde ise Siwa Vahası yatmaktadır. M.Ö. 331 yılında İskender'in bizzat çölü geçerek ulaştığı Amon Tapınağı, onun 'Zeus-Ammon'un oğlu' olduğunu ilan ederek tüm antik dünyada tanrısal bir statü kazanmasını sağlamıştır. Bu olay, Mısır'ın binlerce yıllık dini otoritesinin Yunan siyasi gücüyle birleştiği an olarak tarihe geçmiştir.\n\nAssassin's Creed Origins'in tasvir ettiği Mısır (M.Ö. 49), bu hanedanın çöküş dönemine, yani Kleopatra ve kardeşi XIII. Ptolemaios arasındaki iç savaşa denk gelir. Bu dönemde Mısır, tarımsal zenginliği ve stratejik konumu nedeniyle yükselen güç Roma'nın en büyük hedefi haline gelmiştir. Nil deltası, sağladığı devasa tahıl üretimiyle Roma'nın devasa nüfusunu doyuran bir 'ekmek sepeti' (breadbasket) işlevi görüyordu. İskenderiye ise o dönemin entelektüel merkeziydi. İskenderiye Kütüphanesi, dünyanın dört bir yanından gelen elyazmalarına ev sahipliği yapıyor, Pharos Feneri ise insanlığın mühendislik dehasını simgeliyordu. Ancak mermer sarayların ardında, yerli Mısırlıların Yunan yönetimine karşı duyduğu derin bir huzursuzluk vardı. Yerli halkın vergiler altında ezilmesi ve geleneksel Mısır tapınaklarının Yunan etkisine girmesi, 'Medjay' gibi eski koruyucu sınıfların işlevini yitirmesine ve toplumun radikalleşmesine yol açmıştır. Bayek karakteri üzerinden anlatılan 'Gizli Olanlar'ın doğuşu, aslında bu yozlaşmış devlet düzenine ve yabancı baskısına karşı yerel bir direnişin metaforudur.\n\nSosyal hiyerarşi açısından Ptolemaios dönemi oldukça katıydı. En üstte Grek asıllı yönetici sınıf, ortada Helenleşmiş Mısırlılar ve Yahudiler, en altta ise tarlalarda çalışan köylü Mısırlılar yer alıyordu. Bu sınıfsal ayrım, dilde de kendini gösteriyordu; yönetim dili Grekçe iken, halk Demotik Mısırça konuşmaya devam ediyordu. Kleopatra'nın tarihteki önemi, Mısırça konuşmayı öğrenen ilk Ptolemaios hükümdarı olması ve bu sayede halkın desteğini kazanmaya çalışmasıdır. Ancak Julius Caesar ve daha sonra Mark Antony ile olan ilişkileri, Mısır'ın kaderini Roma'nın iç çekişmelerine bağlamıştır. Actium Savaşı'ndaki (M.Ö. 31) yenilginin ardından Mısır'ın Roma eyaleti olması, antik dünyanın en uzun süreli medeniyetlerinden birinin resmen sona ermesi ve Orta Çağ'a giden yolda ilk taşların döşenmesi anlamına geliyordu. Arkeolojik buluntular, o dönemdeki tapınakların hem Mısır hiyeroglifleriyle hem de Grekçe yazıtlarla dolu olduğunu, iki kültürün birbirini nasıl dönüştürdüğünü kanıtlamaktadır.",
    "accuracyNote": "Origins, arkeolojik ve mimari doğruluk açısından video oyun tarihindeki en iddialı projelerden biridir. Ubisoft, Jean-Claude Golvin gibi ünlü arkeologlarla çalışarak Memfis, İskenderiye ve Kyrene gibi şehirleri o dönemdeki halleriyle yeniden inşa etmiştir. Özellikle 'Discovery Tour' modu, oyunu bir tarih laboratuvarına dönüştürür. Ancak Kleopatra'nın karakteri, tarihi kayıtlardaki entelektüel ve stratejik dehasından ziyade popüler kültürdeki 'baştan çıkarıcı' imajına biraz daha yakındır.",
    "whyInteresting": "Siwa Vahası, o dönemde 'dünyanın sınırı' olarak kabul edilirdi. Oraya giden yol o kadar tehlikeliydi ki, İskender'in ordusunun kum fırtınalarında kaybolmaktan 'gökyüzünden inen kuşlar' sayesinde kurtulduğu anlatılır. Bu vaha, Mısır'ın çöl derinliklerindeki en gizemli ve korunmuş dini sığınağıydı."
  },
  "ac-odyssey-athens": {
    "realHistory": "M.Ö. 431 - 404 yılları arasında süregelen Peloponez Savaşı, antik Yunan dünyasının intiharı olarak nitelendirilir. Atina önderliğindeki Delos Birliği ile Sparta önderliğindeki Peloponez Birliği arasındaki bu topyekün savaş, sadece askeri bir çatışma değil, iki farklı yaşam tarzının ve siyasi ideolojinin (Demokrasi vs. Oligarşi) çarpışmasıydı. Atina, bu dönemde Perikles'in liderliğinde 'Altın Çağı'nın zirvesindeydi. Parthenon Tapınağı'nın inşası tamamlanmış, felsefe Sokrates ile sokaklara inmiş, drama ve sanat insanlık tarihinin en yüksek seviyelerine ulaşmıştı. Ancak bu ihtişam, Atina'nın diğer şehir devletlerinden zorla topladığı haraçlarla finanse ediliyordu.\n\nSavaşın patlak vermesiyle Atina stratejisini deniz gücüne dayandırdı. Perikles, Attika bölgesindeki halkı Atina'nın 'Uzun Duvarlar'ı arkasına toplayarak karada Spartalılarla savaşmaktan kaçındı ve ikmali denizden sağladı. Ancak bu yoğun nüfus birikimi, M.Ö. 430'da şehri vuran ve nüfusun üçte birini (ve bizzat Perikles'i) yok eden korkunç bir veba salgınına yol açtı. Assassin's Creed Odyssey, bu çaresizlik atmosferini, sokaklardaki ceset yığınlarını ve insanların tanrılara olan inancının nasıl sarsıldığını muazzam bir görsellikle aktarır. Savaşın ilerleyen yıllarında Atina, demokratik sistemin zafiyetlerini (demagogların yükselişi, fevri halk kararları) acı bir şekilde tecrübe etti. M.Ö. 415'teki başarısız Sicilya Seferi, Atina donanmasının bel kemiğini kıran ve sonun başlangıcını getiren en büyük askeri hataydı.\n\nSparta ise bu süreçte sadece askeri disipliniyle değil, aynı zamanda ezeli düşman Pers İmparatorluğu'ndan aldığı altın yardımıyla Atina'nın deniz hakimiyetini sarsmayı başardı. M.Ö. 405'teki Aegospotami Muharebesi ile Atina'nın son donanması da yok edilince, 'deniz imparatorluğu' çöktü ve Atina teslim olmak zorunda kaldı. Savaş sonrası kurulan 'Otuz Tiran' yönetimi, Atina demokrasisine ağır bir darbe vurdu. Ancak bu karanlık dönem, ironik bir şekilde Batı felsefesinin en büyük eserlerinin (Platon'un devlet teorileri gibi) yazılmasına zemin hazırladı. Thukididis'in 'Peloponez Savaşı Tarihi' eseri, bugün hala uluslararası ilişkiler ve strateji biliminin temel taşı kabul edilir ve savaşın 'insan doğasının değişmezliği' üzerine kurulu trajik bir döngü olduğunu anlatır.",
    "accuracyNote": "Odyssey, Atina'nın o dönemdeki canlılığını ve çok renkliliğini başarıyla yansıtır. Tapınakların sadece beyaz mermer değil, parlak renklerle boyalı olduğu gerçeği oyunda vurgulanmıştır. Sokrates, Hipokrat ve Herodot gibi tarihi kişiliklerin tasvirleri, antik metinlerdeki karakter özelliklerine son derece sadıktır. Ancak oyunun kurgusal 'Kült' yapısı, o dönemdeki gerçek dini ve siyasi tarikatlardan ziyade bir komplo teorisi niteliğindedir.",
    "whyInteresting": "Atina demokrasisinde 'Ostracism' adı verilen bir sistem vardı. Vatandaşlar, her yıl çok güçlenen veya tehlikeli buldukları bir kişiyi gizli oylamayla (çömlek parçalarına isim yazarak) 10 yıllığına şehirden sürgün edebilirlerdi. Bu, demokrasinin tiranlığa dönüşmesini engellemek için tasarlanmış radikal bir çözümdü."
  },
  "kcd-bohemia": {
    "realHistory": "1403 yılı Bohemyası (günümüz Çek Cumhuriyeti), Kutsal Roma İmparatorluğu'nun tam kalbinde yer alan, zengin gümüş madenleri ve derin kültürel mirasıyla Avrupa'nın en önemli bölgelerinden biriydi. Ancak bu ihtişam, İmparator IV. Charles'ın ölümünün ardından gelen siyasi kaosla sarsıldı. Charles'ın oğlu Wenceslaus, babasının aksine zayıf ve yetersiz bir hükümdardı; bu durum üvey kardeşi Macaristan Kralı Sigismund'un iştahını kabarttı. Sigismund, Bohemya'yı kontrol altına almak için bir darbe düzenleyerek Wenceslaus'u kaçırdı ve ülkeyi Kuman paralı askerlerinden oluşan ordusuyla yağmalamaya başladı.\n\nKingdom Come: Deliverance, bu gerçek tarihi olayların göbeğinde, Skalitz köyünden bir demirci çırağının (Henry) hikayesini anlatır. Oyunun geçtiği Sasau, Rattay ve Skalitz gibi yerleşkeler, o dönemdeki halleriyle, arkeolojik kazılar ve tarihi haritalar temel alınarak birebir modellenmiştir. 15. yüzyıl başındaki Bohemya, sadece bir savaş alanı değil, aynı zamanda Jan Hus gibi figürlerin önderliğinde 'Hussit Hareketleri'nin (Protestan reformunun öncüsü) filizlendiği bir fikir kazanıydı. Feodalite sistemi çatırdayırken, şövalye sınıfı yerini daha organize ve paralı askerlerden oluşan ordulara bırakıyordu. Savaşın doğası değişiyor, surların önemi artıyor ve toplumsal sınıflar arasındaki gerilim tırmanıyordu.\n\nOyunun en dikkat çekici yanı, Orta Çağ'ın 'pislik içindeki karanlık çağ' imajını değil, güneşli tarlaları, görkemli kiliseleri ve yaşayan, üreten bir toplumu resmetmesidir. O dönemde hijyen, yemek kültürü ve toplumsal hukuk kuralları sanıldığından çok daha karmaşıktı. Örneğin, bir şehre girmek için belirli bir statüye sahip olmanız veya silahlarınızı teslim etmeniz gerekirdi. Şövalye dövüşü, filmlerdeki gibi hızlı ve akrobatik değil, ağır zırhların altında dayanıklılık ve strateji gerektiren ölümcül bir danstı. Kumanların bölgeye gelişi, sadece askeri bir istila değil, aynı zamanda dilleri ve kültürleriyle yerel halkta derin bir travma yaratan bir 'yabancı' istilasıydı. Kingdom Come, bu travmayı ve dönemin ruhunu (Zeitgeist) en küçük ayrıntısına kadar yaşatan eşsiz bir tarihsel simülasyondur.",
    "accuracyNote": "Kingdom Come: Deliverance, 'tarihsel doğruluk' konusunda video oyun tarihindeki en yüksek standartları belirlemiştir. Yapımcılar, o dönemdeki kalelerin mimari planlarını, bitki örtüsünü ve hatta gökyüzündeki yıldızların konumunu bile doğru yansıtmak için profesyonel tarihçilerle çalışmışlardır. Oyunun dövüş sistemi, gerçek Orta Çağ savaş sanatı el kitaplarına (Hema) dayanmaktadır.",
    "whyInteresting": "Oyunun geçtiği Rattay kasabası bugün hala mevcuttur ve oyundaki kilise ile kale kalıntıları ziyaret edilebilir. Oyuncular, 600 yıl önceki sokaklarda aynı binaların arasında yürümenin garip ve büyüleyici hissini bugün bile yaşayabilmektedir."
  }
};

let cards = JSON.parse(fs.readFileSync(path, 'utf8'));
let count = 0;

cards = cards.map(card => {
  if (enrichmentData[card.id]) {
    count++;
    return { ...card, ...enrichmentData[card.id] };
  }
  return card;
});

fs.writeFileSync(path, JSON.stringify(cards, null, 2), 'utf8');
console.log(`Enriched ${count} deep flagship cards successfully.`);
