const fs = require('fs');
const path = 'data/cards.json';

const enrichmentData = {
  "rdr2-frontier": {
    "quickRealityCheck": "İlham Alındı. 1899 yılı, Vahşi Batı'nın (Frontier) resmen kapandığı ve modern yasaların çorak arazilere ulaştığı bir geçiş dönemidir.",
    "mediaChanged": "Oyunda çetelerin hala devasa ordulara karşı savaştığı ve kasabaları ele geçirdiği gösterilir. Gerçekte 1899'da Pinkerton gibi ajanslar ve telegraf hatları sayesinde suç örgütlerinin hayatta kalma şansı neredeyse kalmamıştı. Ayrıca oyundaki 'çete kampları' gerçekte çok daha mobil ve küçük gruplar halindeydi.",
    "realHistory": "19. yüzyılın sonu, Amerikan tarihinde 'Sınırın Kapanışı' (Closing of the Frontier) olarak bilinen dramatik bir dönemi temsil eder. 1890 nüfus sayımı verileri, artık kıtanın bir ucundan diğer ucuna kadar yerleşimin tamamlandığını ve 'vahşi' olarak tanımlanabilecek sahipsiz toprakların kalmadığını ilan etmiştir. Bu, Red Dead Redemption 2'nin temel trajedisidir: Suçluların kaçabileceği hiçbir yer kalmamıştır.\n\n### Pinkerton Ulusal Dedektiflik Ajansı ve Özel Güvenlik\nOyunda ana düşman olan Pinkerton Ajansı, o dönemde gerçekten de hükümetin yetersiz kaldığı yerlerde 'özel ordu' gibi çalışan devasa bir kuruluştur. Allan Pinkerton tarafından kurulan ajans, sadece kanun kaçaklarını yakalamakla kalmamış, aynı zamanda sanayileşen Amerika'da işçi grevlerini kırmak ve sendikaları bastırmak için de kullanılmıştır. Pinkertonlar, o dönemin 'yarı yasal' kiralık ordularıydı ve yöntemleri bazen peşinde oldukları suçlulardan daha acımasız olabiliyordu. Bu durum, oyunun alt metnindeki 'medeniyetin acımasızlığı' temasını tarihsel olarak doğrular.\n\n### Sanayileşme ve Ekonomik Dönüşüm\n1899 Amerika'sı, tarım toplumundan sanayi toplumuna geçişin zirvesindedir. Petrolün bulunması, çelik üretiminin artması ve demiryollarının kıtayı bir ağ gibi sarması, kovboyların ve bağımsız avcıların ekonomik rollerini bitirmiştir. Büyük holdingler, küçük toprak sahiplerini ve yerli halkı yerinden ederek devasa kaynaklara el koymaya başlamıştır. Bu süreçte yerli halkın (Kızılderililerin) son direnişleri de kırılmış ve rezervasyonlara hapsedilmişlerdir. Vahşi Batı, artık bireysel bir macera alanı değil, kurumsal bir sömürü platformu haline gelmiştir.\n\n### Telegraf ve Bilginin Hızı\nModern hukuk sisteminin gelişimine paralel olarak, 'Self-Help' (Kendi adaletini arama) kültürü yerini mahkemelere ve kurumsal hapishanelere bırakmıştır. Telegrafın icadı, bir suçlunun eşkalinin saniyeler içinde tüm eyaletlere yayılmasını sağlayarak suç dünyasının lojistiğini imkansız kılmıştır. Eskiden bir atın hızına bağlı olan bilgi, artık ışık hızıyla yayılıyordu. Oyundaki Saint Denis şehri, bu 'modern kirlilik ve düzen' sentezinin en başarılı tasvirlerinden biridir; burada artık atların yerini yavaş yavaş elektrikli tramvaylar ve otomobiller almaktadır.\n\n### Vahşi Batı Efsanesinin Sonu ve Nostalji\nGerçek Vahşi Batı, medyada anlatılanın aksine sadece silahşörlerden ibaret değildi. Çoğunlukla tozlu tarlalarda hayatta kalmaya çalışan göçmenler, madenciler ve demiryolu işçilerinin hikayesiydi. 1899'a gelindiğinde, 'kovboy' yaşam tarzı artık Buffalo Bill'in 'Vahşi Batı Şovu' gibi sirklerde sergilenen birer nostalji öğesine dönüşmüştü. Tarihsel gerçeklikte, Arthur Morgan gibi figürler ya bu yeni düzene ayak uydurmuş ya da bu düzenin çarkları arasında ezilip gitmişlerdir. Red Dead Redemption 2, bu 'eski dünyanın' son nefesini vermesini anlatan hüzünlü bir tarihsel belge niteliğindedir.",
    "whyItMatters": "Sınırın kapanışı, Amerikan karakterinin 'sınırsız özgürlük' idealinden 'kurumsal düzen' gerçeğine geçişini simgeler. Bu dönem, modern Amerika'nın temellerinin atıldığı andır."
  },
  "chernobyl-disaster": {
    "quickRealityCheck": "Çok Yüksek Doğruluk. 26 Nisan 1986'daki patlama ve sonrasındaki kriz yönetimi, teknik ve siyasi açıdan büyük oranda gerçeğe dayanır.",
    "mediaChanged": "Dizideki fizikçi Ulana Khomyuk kurgusal bir karakterdir; felaketi araştıran onlarca Sovyet bilim insanının kolektif bir temsilidir. Ayrıca 'termal patlama' riski dizide biraz dramatize edilmiştir; gerçekte bir buhar patlaması ve ardından grafit yangını asıl yıkımı yaratmıştır.",
    "realHistory": "Çernobil felaketi, sadece bir nükleer kaza değil, Sovyetler Birliği'nin bürokratik, bilimsel ve ahlaki yapısının çöküş belgesidir. 26 Nisan 1986 gece yarısı, 4 numaralı reaktörde yapılan hatalı bir güvenlik testi, reaktörün tasarım kusurlarıyla (RBMK reaktörü) birleşince kontrolsüz bir güç artışına ve ardından buhar patlamasına neden olmuştur.\n\n### RBMK Reaktörü ve Tasarım Kusurları\nRBMK tipi reaktörlerin en büyük kusuru, 'pozitif boşluk katsayısı' denilen ve reaktör ısındıkça reaksiyonun hızlanmasına neden olan bir özelliktir. Daha da önemlisi, kontrol çubuklarının uçlarının grafit olması, çubuklar içeri girerken reaksiyonu kısa süreliğine de olsa hızlandırıyordu. Sovyet bilim dünyasındaki gizlilik ve 'hatasızlık' kültürü, bu bilginin operatörlerden saklanmasına neden olmuştur. Yani kazaya giden yol, yıllar öncesinden bürokrasi tarafından döşenmiştir.\n\n### Tasfiye Memurları: Likidatörlerin Fedakarlığı\nFelaketin ardından radyasyonla savaşan yaklaşık 600.000 kişiye 'Likidatör' adı verilmiştir. Bunlar arasında enkazdaki grafit parçalarını elleriyle atan askerler (Biyo-robotlar), reaktörün altına tünel kazan madenciler ve zehirli suları boşaltmak için havuza giren dalgıçlar vardır. Bu insanların çoğu, radyasyonun etkilerini tam bilmeden veya vatan sevgisiyle kendilerini feda etmişlerdir. Onların bu fedakarlığı olmasaydı, radyoaktif kirlilik tüm Avrupa'yı yaşanmaz hale getirebilirdi. Bu kitlesel seferberlik, Sovyet sisteminin son büyük 'vatanperverlik' sınavıydı.\n\n### Pripyat ve Sessiz Tahliye\nModel şehir Pripyat, patlamadan sonraki 36 saat boyunca tahliye edilmemiştir. Sovyet yönetimi, felaketin boyutlarını dünyadan ve kendi halkından gizlemeye çalışmıştır. Ancak İsveç'teki bir nükleer santralde tespit edilen radyoaktif bulutlar, gerçeğin ortaya çıkmasını zorunlu kılmıştır. Pripyat halkına 'sadece 3 günlüğüne' ayrılacakları söylenmiş, ancak bir daha hiç kimse evine dönememiştir. Bugün Pripyat, insanın doğa karşısındaki yenilgisinin en somut ve hüzünlü anıtı olarak durmaktadır. Şehirdeki dönme dolap ve terk edilmiş sınıflar, soğuk savaşın sonunun en güçlü sembolleridir.\n\n### Siyasi Sonuçlar: Gorbaçov ve SSCB'nin Çöküşü\nMihail Gorbaçov, daha sonra yaptığı açıklamalarda 'Çernobil'in, Sovyetler Birliği'nin çöküşünün asıl nedeni olabileceğini' belirtmiştir. Devletin halkını korumadaki yetersizliği, bilimsel yalanlar ve felaketin ekonomik maliyeti, Glasnost (Açıklık) politikasını kaçınılmaz kılmış ve sistemin meşruiyetini bitirmiştir. Çernobil, nükleer enerjinin riskleri konusunda küresel bir paradigma değişimi yaratmış ve yeşil hareketlerin güçlenmesini sağlamıştır. Felaket, 'teknoloji tek başına yeterli değildir; şeffaflık ve etik de gereklidir' mesajını tarihe kanla kazımıştır.",
    "whyItMatters": "Çernobil, teknolojik bir sistemin değil, kapalı ve şeffaf olmayan bir siyasi sistemin felaketiydi. Bilginin gizlenmesinin fiziksel bir yıkıma nasıl dönüşebileceğinin en büyük dersidir."
  },
  "oppenheimer-trinity": {
    "quickRealityCheck": "Çok Yüksek Doğruluk. Manhattan Projesi'nin işleyişi, Trinity testi ve sonrasındaki siyasi cadı avı tarihsel tutanaklara dayanır.",
    "mediaChanged": "Filmde Oppenheimer ve Einstein arasındaki ilişki biraz daha sembolik ve sık gösterilmiştir; gerçekte ilişkileri daha mesafeliydi. Ayrıca Strauss ile olan rekabeti drama için biraz daha keskinleştirilmiştir. Bazı bilimsel tartışmaların süresi görsellik için kısaltılmıştır.",
    "realHistory": "J. Robert Oppenheimer önderliğindeki Manhattan Projesi, bilimin 'masumiyetini kaybettiği' ve insanlığın kendi yok oluşunu tasarlayabildiği bir çağın başlangıcıdır. 1942'de başlayan bu devasa gizli operasyon, müttefiklerin Nazi Almanyası'ndan önce atom bombasına ulaşma yarışıdır.\n\n### Los Alamos ve Bilimsel Seferberlik\nLos Alamos, New Mexico'nun ücra bir köşesinde sıfırdan inşa edilmiş gizli bir şehirdi. Burası dünyanın en parlak fizikçilerini (Enrico Fermi, Richard Feynman, Hans Bethe vb.) bir araya getiren devasa bir laboratuvardı. Bilim insanları burada sadece fizik problemleriyle değil, aynı zamanda askeri disiplin, gizlilik baskısı ve etik ikilemlerle de boğuştular. Proje o kadar gizliydi ki, işçilerin çoğu ne üzerine çalıştıklarını bile bilmiyordu. Kadın matematikçiler ve mühendisler, projenin görünmez ama kritik kahramanlarıydı.\n\n### Trinity Testi ve 'Gadget'\n'Gadget' kod adlı ilk atom bombası, 16 Temmuz 1945 sabahı saat 05:29'da patlatıldı. Patlamanın şiddeti, bilim insanlarının bile tahminlerini aşmıştı. Oppenheimer, o anı daha sonra Bhagavad Gita'dan alıntı yaparak şöyle anlatmıştır: 'Şimdi ben ölüm oldum, dünyaların yok edicisi.' Bu test, insanlık tarihinin atom çağına girdiği andır. Testin başarılı olması, savaşın sonunu getirse de, insanlığın eline daha önce hiç sahip olmadığı kadar büyük bir yıkım gücü vermiştir.\n\n### Etik Kırılma ve Hidrojen Bombası Tartışması\nJaponya'ya atılan bombaların ardından Oppenheimer, vicdani bir yük altına girmiştir. Savaştan sonra nükleer silahların uluslararası kontrolünü savunmuş ve çok daha güçlü olan 'Hidrojen Bombası' (Süper) projesine karşı çıkmıştır. Bu duruşu, onu askeri kanat ve Edward Teller gibi 'şahin' bilim insanlarıyla karşı karşıya getirmiştir. Oppenheimer'a göre, atom bombası bir 'savunma' silahı olsa da, hidrojen bombası sadece 'soykırım' silahı olabilirdi. Bilim topluluğu içindeki bu etik bölünme, soğuk savaşın ilk yıllarındaki stratejik tartışmaları belirlemiştir.\n\n### 1954 Güvenlik Duruşması ve Siyasi Çöküş\nSoğuk Savaş'ın başlaması ve McCarthy döneminin 'komünist avı', Oppenheimer'ın sonunu hazırlamıştır. Lewis Strauss liderliğindeki AEC (Atom Enerjisi Komisyonu), Oppenheimer'ın geçmişteki sol eğilimli bağlantılarını bahane ederek onun güvenlik yetkisini iptal etmek için bir duruşma düzenlemiştir. Bu duruşma, aslında Oppenheimer'ı siyaseten etkisiz hale getirme operasyonuydu. 1954'te yetkisi elinden alınan Oppenheimer, bilim dünyasından dışlanmasa da siyasi etkisini tamamen yitirmiş ve trajik bir figüre dönüşmüştür. Bu olay, bilimin siyasetle olan tehlikeli ilişkisinin en somut dökümanıdır.",
    "whyItMatters": "Oppenheimer'ın hikayesi, bilim insanının yarattığı ürün üzerindeki ahlaki sorumluluğunu ve devlet gücünün bilim üzerindeki baskıcı otoritesini simgeler."
  },
  "ancient-roman-day": {
    "quickRealityCheck": "Gerçek. Bir Roma vatandaşının günü, modern yaşamla şaşırtıcı benzerlikler taşır; iş, yemek, spor ve eğlence üzerine kuruluydu.",
    "mediaChanged": "Dizilerde Romalılar sürekli ya savaşta ya da sefahattedir. Gerçekte sıradan bir vatandaş (Plebler), şafak vaktinde kalkıp akşamüstüne kadar çalışır, ardından ücretsiz halk hamamlarına giderek sosyalleşirdi. Ayrıca Romalıların sürekli yatarak yemek yediği miti sadece çok zenginler için geçerliydi.",
    "realHistory": "Romalılar için gün 'Salutatio' ile başlardı. Bu, himaye altındaki kişilerin (client) sabah erkenden patronlarını (patronus) ziyaret ederek sadakatlerini göstermeleri ve o günkü yardımlarını almaları ritüeliydi. Ardından Forum'da işler halledilir, ticaret yapılır ve davalar izlenirdi. Öğleden sonra iş biter ve tüm şehir 'Thermae' adı verilen hamamlara akın ederdi. Hamamlar sadece temizlik değil, aynı zamanda kütüphanelerin, spor alanlarının ve yemek tezgahlarının bulunduğu devasa sosyal kulüplerdi.\n\n### Sosyal Yardımlar ve Ekmek Sistemi\nRoma'da hayat, 'Annona' (bedava tahıl) ve 'Circenses' (eğlenceler) sayesinde, işsiz kitlelerin bile bir rutine ve temel ihtiyaçlara sahip olduğu organize bir sistemdi. Roma devleti, halkın ayaklanmasını engellemek için bu sosyal güvenlik ağını titizlikle yönetirdi. Akşam yemeği (Cena), ailenin ve dostların bir araya geldiği en önemli ritüeldi. Roma'da yaşayan bir Pleb için hayat zor olsa da, bugünkü birçok modern şehirden daha fazla sosyal imkana sahipti. Roma günlük yaşamı, modern 'kentsel yaşam' modelinin (sosyal alanlar, organize çalışma saatleri, devlet yardımları) ilk başarılı prototipidir.",
    "whyItMatters": "Roma günlük yaşamı, kitlelerin nasıl yönetileceği ve bir şehrin nasıl 'yaşayan bir organizma' haline getirileceği konusunda batı medeniyetine temel rehber olmuştur."
  }
};

let cards = JSON.parse(fs.readFileSync(path, 'utf8'));
let count = 0;

cards = cards.map(card => {
  if (enrichmentData[card.id]) {
    count++;
    return { ...card, ...enrichmentData[card.id] };
  }
  return card;
});

fs.writeFileSync(path, JSON.stringify(cards, null, 2), 'utf8');
console.log(`Enriched final batch of ${count} cards to premium standards.`);
