const fs = require('fs');
const path = 'data/cards.json';

const enrichmentData = {
  "ac-origins-siwa": {
    "realHistory": "Ptolemaios dönemi Mısır'ı (M.Ö. 49), Firavunlar döneminin ihtişamı ile Greko-Romen dünyasının yükselişinin çarpıştığı hibrit bir dönemdir. Siwa Vahası, sadece çölün ortasındaki bir su kaynağı değil, Büyük İskender'in 'Zeus-Ammon'un oğlu' olduğunu ilan ettiği kutsal Amon Tapınağı'na ev sahipliği yapmasıyla ünlüdür. Bu dönemde Mısır, tarımsal zenginliği (Nil deltası sayesinde) nedeniyle Roma'nın en önemli 'tahıl ambarı' olmuştur.\n\nAssassin's Creed Origins'in tasvir ettiği Mısır, arkeologların ve tarihçilerin yardımıyla inşa edilmiş muazzam bir dijital rekonstrüksiyondur. İskenderiye Kütüphanesi'nden Gize Piramitleri'ne kadar her yer, dönemin mimari dokusuna ve toplumsal hiyerarşisine sadık kalınarak resmedilmiştir. Ancak siyasi olarak, Kleopatra ve kardeşi XIII. Ptolemaios arasındaki iç savaş, Mısır'ın bağımsızlığının son demlerini yaşadığı, Roma'nın (Sezar üzerinden) bölgeye kalıcı olarak yerleştiği trajik bir süreçtir. Mısır halkı, binlerce yıllık dini geleneklerini korumaya çalışırken, yönetici elitlerin Yunan kültürüyle harmanlanmış olması toplumda derin bir kimlik krizine yol açmıştır.",
    "accuracyNote": "Oyun, Discovery Tour moduyla zaten bir eğitim aracı olarak tasarlanmıştır. Mimari ve coğrafi doğruluk oranı, ana akım medyadaki diğer tüm Mısır tasvirlerinden daha yüksektir.",
    "whyInteresting": "Siwa Vahası'ndaki kahinler, antik dünyanın en etkili siyasi figürlerinden biriydi. Büyük İskender'in oraya gitmesi tesadüf değildi; zira Amon'un onayını almak, tüm Mısır ve Pers dünyasında meşruiyetini perçinlemek anlamına geliyordu."
  },
  "ac-odyssey-athens": {
    "realHistory": "Peloponez Savaşı (M.Ö. 431-404), Atina liderliğindeki Delos Birliği ile Sparta liderliğindeki Peloponez Birliği arasındaki topyekün bir güç mücadelesidir. Atina, bu dönemde Perikles'in liderliğinde demokrasinin, felsefenin ve sanatın zirvesindeydi; ancak bu ihtişam, Atina'nın diğer şehir devletleri üzerindeki baskıcı emperyal politikasıyla finanse ediliyordu. Atina'nın 'Altın Çağı', sadece felsefi tartışmalardan ibaret değil, aynı zamanda veba salgınlarının, yıkıcı deniz savaşlarının ve demokratik sistemin iç çatışmalarla sarsıldığı karanlık bir dönemdir.\n\nSokrates gibi figürlerin sokaklarda dolaşıp insanları sorguladığı bu şehir, aynı zamanda sofistlerin yükseldiği ve hitabet sanatının bir silah olarak kullanıldığı bir merkezdi. Atina'nın surları (Uzun Duvarlar), şehri ve limanı bir kale gibi koruyarak Atina'nın deniz gücüne dayalı stratejisinin temelini oluşturuyordu. Ancak Sparta'nın askeri disiplini ve İran'ın (Persler) altınları, sonunda Atina'nın deniz hakimiyetini kırarak klasik Yunan dünyasının dengesini sonsuza dek bozmuştur.",
    "accuracyNote": "Assassin's Creed Odyssey, Atina'nın renkli ve canlı atmosferini, heykellerin boyalı olduğu (beyaz mermer değil!) gerçeğini yansıtarak muazzam bir iş çıkarır. Perikles ve Sokrates gibi figürlerin tasvirleri tarihsel karakterlerine oldukça sadıktır.",
    "whyInteresting": "Atina demokrasisinde her vatandaşın (kadınlar ve köleler hariç) doğrudan yönetimde söz hakkı vardı. Ancak bu sistem, halkın hitabet ustaları tarafından kolayca manipüle edilmesine (demagoji) ve feci askeri kararlar alınmasına (Sicilya Seferi gibi) neden olmuştur."
  },
  "kcd-bohemia": {
    "realHistory": "1403 yılı Bohemyası (Kutsal Roma İmparatorluğu), Kral IV. Wenceslaus ve üvey kardeşi Sigismund arasındaki taht kavgasıyla iç savaşa sürüklenmişti. Bu dönem, Orta Çağ'ın son demleridir; feodal sadakatlerin sarsıldığı, dini reform hareketlerinin (Jan Hus gibi) filizlendiği ve şövalyelik idealinin yerini daha profesyonel paralı asker ordularına bıraktığı bir süreçtir. Kingdom Come: Deliverance, bu dönemi 'fantastik' unsurlar olmadan, en küçük ayrıntısına kadar (yemek pişirme, kılıç eğitimi, hijyen) yansıtmaya odaklanır.\n\nOyunun geçtiği Sasau, Rattay ve Skalitz gibi yerleşkeler, o dönemin Bohemya mimarisini ve kırsal yaşamını birebir yansıtır. Tarihsel olarak Bohemya, Avrupa'nın gümüş madenleri sayesinde en zengin bölgelerinden biriydi; bu da onu dış saldırılara ve iç hırslara açık hale getiriyordu. Sigismund'un Kuman paralı askerlerini kullanarak köyleri yağmalaması, o dönemin savaş hukukunun ne kadar acımasız ve sivil halk için yıkıcı olduğunu gösteren gerçek bir tarihsel trajedidir.",
    "accuracyNote": "KCD, kılıç dövüşü tekniklerinden bitki bilimine, kıyafetlerin katmanlarından toplumsal sınıfların birbirine hitap şekline kadar video oyun tarihindeki en doğru Orta Çağ simülasyonudur.",
    "whyInteresting": "Oyunun yapımcıları, o dönemdeki kalelerin ve köylerin konumlarını belirlemek için arkeolojik kazı haritalarını ve hava fotoğraflarını kullanmışlardır. Bu sayede 1403 Bohemyası'nda gerçekten de o yollarda yürüyormuşsunuz hissi yaratılmıştır."
  },
  "ghost-tsushima-invasion": {
    "realHistory": "1274 yılındaki Moğol istilası, Japonya tarihinde bir dönüm noktasıdır. Kubilay Han'ın önderliğindeki Moğol-Kore filosu, Tsushima adasını istila ederek ana karaya bir köprü kurmayı hedeflemiştir. Samuraylar, o döneme kadar 'bire bir düello' geleneğine dayalı bir savaş anlayışına sahipti; ancak Moğolların grup taktikleri, ateşli silahları (bombalar) ve acımasız savaş disiplini, Japonların savaş doktrinini tamamen değiştirmek zorunda kalmalarına neden olmuştur.\n\nTarihsel olarak 'Ghost of Tsushima'daki Jin Sakai karakteri kurgusaldır; ancak Moğol ordusunun teknolojik üstünlüğü ve Japonların bu tehdit karşısındaki çaresizliği gerçektir. Japonya'yı kurtaran asıl unsur, ikinci istila sırasında (1281) çıkan ve Moğol donanmasını yok eden 'Kamikaze' (İlahi Rüzgar) adlı tayfundur. Bu olay, Japonların kendilerini 'tanrılar tarafından korunan bir millet' olarak görmelerine neden olan uzun süreli bir inanç sisteminin temelini atmıştır.",
    "accuracyNote": "Oyun, Kurosawa filmlerinin estetiğini takip ettiği için bazı samuray zırhları ve Bushido felsefesi unsurları 13. yüzyıldan ziyade 16. yüzyıla (Sengoku dönemi) aittir. 13. yüzyıl samurayları genellikle okçuluk odaklıydı.",
    "whyInteresting": "Moğol istilaları, Japonya'da ilk kez tüm klanların tek bir düşmana karşı birleşmesini sağlamıştır. Bu birleşme, Japonya'da merkeziyetçi bir yapının temellerini atan sosyal bir dönüşümü tetiklemiştir."
  },
  "chernobyl-disaster": {
    "realHistory": "26 Nisan 1986'da Çernobil Nükleer Santrali'nin 4. reaktöründe meydana gelen patlama, insanlık tarihinin en büyük nükleer felaketidir. Felaket, sadece teknik bir hata (RBMK reaktör tasarımı ve test hataları) değil, aynı zamanda Sovyetler Birliği'nin bürokratik hiyerarşisi, gizlilik kültürü ve 'her şey yolunda' raporlama geleneğinin bir sonucudur. Felaketin ardından Pripyat şehrinin tahliyesi 36 saat gecikmiş, bu da binlerce insanın yüksek dozda radyasyona maruz kalmasına neden olmuştur.\n\n'Likidatör' olarak bilinen yüz binlerce itfaiyeci, madenci ve asker, felaketi kontrol altına almak için hayatlarını hiçe sayarak enkaz altında çalışmışlardır. Reaktörün üzerine 'Lahit' adı verilen devasa beton bir yapı inşa edilerek radyasyon sızıntısı durdurulmaya çalışılmıştır. Tarihsel olarak Çernobil, Mihail Gorbaçov'un da belirttiği gibi, Sovyetler Birliği'nin çöküşünü hızlandıran en büyük katalizörlerden biri olmuştur; çünkü devletin halkını korumadaki yetersizliği ve yalanları tüm dünyada meşruiyet kaybına yol açmıştır.",
    "accuracyNote": "Chernobyl dizisi, felaketin teknik detaylarını, likidatörlerin hikayelerini ve Sovyet döneminin görsel atmosferini muazzam bir doğrulukla yansıtır. Ulana Khomyuk karakteri, felaketi araştıran onlarca bilim insanını temsil eden kurgusal bir birleşimdir.",
    "whyInteresting": "Çernobil'in çevresindeki 'Yasak Bölge' (Exclusion Zone), bugün insan müdahalesi olmadan doğanın nasıl hızla geri döndüğünü gösteren devasa bir yaban hayatı laboratuvarı haline gelmiştir."
  },
  "oppenheimer-trinity": {
    "realHistory": "Manhattan Projesi (1942-1946), atom bombasının geliştirilmesi için yürütülen gizli ve devasa bir askeri-bilimsel operasyondur. J. Robert Oppenheimer liderliğindeki Los Alamos Laboratuvarı, dünyanın en zeki fizikçilerini bir araya getirerek nükleer fisyonu bir silaha dönüştürmeyi başarmıştır. 16 Temmuz 1945'teki 'Trinity' testi, insanlığın atom çağının başladığı ve savaşın doğasının sonsuza dek değiştiği andır.\n\nTarihsel olarak bu proje, sadece bir bilimsel başarı değil, aynı zamanda 'bilimin masumiyetini kaybettiği' etik bir kırılma noktasıdır. Oppenheimer, testin başarısının ardından Bhagavad Gita'dan alıntı yaparak 'Şimdi ben ölüm oldum, dünyaların yok edicisi' demiştir. Bombaların Hiroşima ve Nagazaki'de kullanılmasının ardından, projenin içindeki birçok bilim insanı (Oppenheimer dahil), nükleer silahların kontrolü ve nükleer silahlanma yarışı konusunda derin vicdani ve siyasi çatışmalar yaşamışlardır. Bu süreç, 1950'lerde Oppenheimer'ın 'McCarthyism' kurbanı olarak güvenlik yetkisinin elinden alınmasıyla sonuçlanan trajik bir sonla taçlanmıştır.",
    "accuracyNote": "Christopher Nolan'ın Oppenheimer filmi, hem bilimsel tartışmaları hem de Oppenheimer'ın 1954'teki duruşma sürecini tarihsel kayıtlara son derece sadık kalarak aktarır. Richard Feynman ve Albert Einstein gibi figürlerin rolleri de tarihsel gerçeklerle örtüşür.",
    "whyInteresting": "Manhattan Projesi o kadar gizliydi ki, dönemin Başkan Yardımcısı Harry Truman bile projenin varlığını ancak Roosevelt ölüp kendisi başkan olduğunda öğrenmiştir."
  },
  "gladiator-colosseum": {
    "realHistory": "Kolezyum (Flavian Amfitiyatrosu), M.S. 80 yılında İmparator Vespasian tarafından inşa edilen ve 50.000 ila 80.000 seyirci kapasitesine sahip olan antik dünyanın mühendislik şaheseridir. Sanılanın aksine, Kolezyum sadece bir 'katliam' yeri değil, Roma devletinin gücünü, teknolojisini ve sosyal hiyerarşisini sergilediği bir tiyatro sahnesiydi. Gladyatör dövüşleri, vahşi hayvan avları (Venatio) ve hatta arenanın suyla doldurulup gemi savaşlarının (Naumachia) canlandırıldığı muazzam prodüksiyonlara ev sahipliği yapardı.\n\nKolezyum'un altında 'Hypogeum' adı verilen karmaşık bir tünel ve asansör sistemi vardı; bu sayede gladyatörler ve hayvanlar aniden arenanın ortasında belirebilirdi. Bu, Roma halkının heyecanını zirvede tutan bir 'gösteri endüstrisi'ydi. Kolezyum, aynı zamanda Roma toplumunun sınıfsal yapısını da yansıtıyordu; en alt sırada imparator ve senatörler, orta sırada özgür vatandaşlar, en üstte ise yoksullar ve kadınlar otururdu. 500 yıl boyunca kullanılan bu yapı, Roma İmparatorluğu'nun hem ihtişamının hem de 'ekmek ve oyunlar' (Panem et Circenses) politikasının en somut mirasıdır.",
    "accuracyNote": "Gladiator filmi, atmosfer ve Kolezyum'un heybeti konusunda başarılı olsa da, Marcus Aurelius ve Commodus dönemindeki siyasi olayları dramatize etmek için değiştirmiştir. Örneğin Commodus arenada ölmemiştir (banyoda boğulmuştur).",
    "whyInteresting": "Kolezyum'un açılış oyunları 100 gün sürmüş ve bu süreçte 9000'den fazla hayvan öldürülmüştür. Ayrıca seyircileri güneşten korumak için 'Velarium' adı verilen, denizciler tarafından yönetilen devasa bir tente sistemi kullanılırdı."
  }
};

let cards = JSON.parse(fs.readFileSync(path, 'utf8'));

cards = cards.map(card => {
  if (enrichmentData[card.id]) {
    return { ...card, ...enrichmentData[card.id] };
  }
  return card;
});

fs.writeFileSync(path, JSON.stringify(cards, null, 2), 'utf8');
console.log('Enriched 5 cards successfully.');
