const fs = require('fs');
const path = 'data/cards.json';

const enrichmentData = {
  "ac-origins-siwa": {
    "realHistory": "Ptolemaios dönemi Mısır'ı (M.Ö. 49), antik dünyanın en dramatik dönüşüm noktalarından biridir. Büyük İskender'in ölümünün ardından generali Ptolemaios Soter tarafından kurulan hanedan, Mısır'ın binlerce yıllık geleneklerini Yunan kültürüyle harmanlamış (Hellenistik dönem), ancak bu durum yerli halk ile yönetici elit arasında derin uçurumlar yaratmıştır. Siwa Vahası, bu bağlamda hem dini hem de siyasi bir merkezdir. Büyük İskender'in bizzat çölü geçerek ulaştığı Amon Tapınağı, onun 'Zeus-Ammon'un oğlu' olduğunu ilan ederek firavunluk meşruiyetini kazandığı yerdir.\n\nAssassin's Creed Origins, bu dönemi sadece bir arka plan olarak değil, yaşayan bir dünya olarak kurgular. İskenderiye, o dönemde dünyanın bilim ve kültür başkentiydi; İskenderiye Kütüphanesi ve Pharos Feneri, insanlık kibrinin ve bilgisinin sembolleriydi. Ancak Kleopatra ve kardeşi XIII. Ptolemaios arasındaki iç savaş, Mısır'ın son bağımsız nefesleridir. Julius Caesar'ın İskenderiye'ye gelişi ve Kleopatra ile olan ittifakı, Mısır'ın artık bir 'Roma eyaleti' olma yoluna girmesini kesinleştirmiştir. Oyunun tasvir ettiği Medjay sınıfı (Bayek), aslında Eski Krallık'tan beri var olan ama Ptolemaios döneminde işlevini yitirmiş bir sınır muhafız birliğini temsil eder. Bu, eski dünyanın muhafızları ile yeni dünyanın emperyal güçleri arasındaki kaçınılmaz çatışmanın bir metaforudur. Mısır'ın tahıl ambarları Roma'yı beslemeye başladığında, firavunların gizemli dünyası yerini Roma'nın bürokratik düzenine bırakmıştır. Arkeolojik olarak oyun, Memfis'in çökmekte olan tapınaklarından İskenderiye'nin mermer saraylarına kadar her ayrıntıda dönemin sosyo-politik gerilimini yansıtır.",
    "accuracyNote": "Oyun, Discovery Tour moduyla bilimsel bir rekonstrüksiyon niteliğindedir. Ptolemaios dönemindeki kıyafetler, dillerin karışımı (Kıpti ve Grekçe) ve tarım yöntemleri tarihsel verilere dayandırılmıştır.",
    "whyInteresting": "Siwa Vahası'ndaki kahinler, antik dünyada 'Geleceği gören tek otorite' olarak kabul edilirdi. Büyük İskender'in oraya gitmesi, sadece bir hac ziyareti değil, tüm doğu dünyasına 'Ben bir tanrıyım' mesajını vermek için yapılmış en büyük halkla ilişkiler hamlesidir."
  },
  "ac-odyssey-athens": {
    "realHistory": "M.Ö. 5. yüzyıl Atinası, insanlık tarihinin en parlak 'Altın Çağı'nı (Perikles Dönemi) yaşarken aynı zamanda Peloponez Savaşı'nın yıkımıyla sarsılıyordu. Atina, bir yanda Parthenon Tapınağı gibi mimari harikalar inşa edip Sokrates, Platon ve Sofokles gibi dehalara ev sahipliği yaparken, diğer yanda Delos Birliği aracılığıyla diğer Yunan şehir devletlerini haraca bağlayan emperyalist bir güçtü. Peloponez Savaşı (M.Ö. 431-404), sadece Atina ve Sparta arasındaki bir çatışma değil, 'Demokrasi' ile 'Oligarşi' arasındaki ideolojik bir savaştı.\n\nAtina demokrasisi, tüm özgür erkek vatandaşların doğrudan katılımına dayalıydı; ancak bu sistem, savaşın getirdiği kıtlık, veba salgınları ve demagogların manipülasyonlarıyla zayıflamıştır. M.Ö. 430'da şehri vuran ve nüfusun üçte birini (Perikles dahil) öldüren büyük veba salgını, Atina'nın psikolojik ve askeri çöküşünün en büyük nedenidir. Assassin's Creed Odyssey, bu dönemi 'kaosun ve düzenin' çatıştığı bir platform olarak sunar. Atina'nın 'Uzun Duvarları', şehri denizden gelen ikmale bağlarken karadan Sparta kuşatmasına karşı tek koruma kalkanıydı. Savaşın sonunda Atina'nın deniz gücünün (Trireme donanması) yok edilmesi, Klasik Yunan medeniyetinin zirve noktasının sonu olmuş ve Yunan dünyasının Pers etkisine açık hale gelmesine neden olmuştur.",
    "accuracyNote": "Oyun, Atina'nın beyaz mermerden ibaret olduğu mitini yıkarak heykellerin ve tapınakların orijinalindeki gibi canlı renklerle boyalı olduğunu gösterir. Perikles'in cenaze töreni söylevi gibi tarihi anlar, Thukididis'in kayıtlarına sadık kalınarak dramatize edilmiştir.",
    "whyInteresting": "Atina'daki 'Ostracism' (Sürgün) sistemi, halkın çok güçlenen veya tehlikeli bulduğu siyasetçileri 10 yıllığına şehirden kovma hakkına sahip olduğu benzersiz bir demokratik 'öz savunma' mekanizmasıydı."
  },
  "ghost-tsushima-invasion": {
    "realHistory": "1274 ve 1281 yıllarındaki Moğol istilaları, Japonya'nın dış bir güç tarafından fethedilmeye en çok yaklaştığı anlardır. Kubilay Han önderliğindeki Moğol İmparatorluğu, o dönemin en gelişmiş donanmasını ve kuşatma teknolojisini kullanarak Tsushima adasına saldırmıştır. Samuraylar, o güne kadar 'bire bir onurlu düello' geleneğine sahipti ve savaş alanında isimlerini bağırarak düşmanını düelloya davet ederlerdi. Ancak Moğollar, disiplinli okçu mangaları, barutlu patlayıcılar (tetsuhau) ve toplu saldırı taktikleriyle bu geleneği paramparça ettiler.\n\nGhost of Tsushima'daki Jin Sakai'nin 'Hayalet' olma süreci, aslında Japon savaş doktrininin bu acımasız yeni gerçekliğe uyum sağlama çabasını temsil eder. Tarihsel olarak samuraylar, Moğol tehdidi karşısında kılıç kullanımından ziyade okçuluk (Yabusame) ve grup savunmasına yönelmişlerdir. Japonya'yı kurtaran asıl mucize, Moğol donanmasını iki kez yok eden büyük fırtınalardır. Bu fırtınalara 'Kamikaze' (İlahi Rüzgar) adı verilmiştir. Bu istila girişimi, Japonya'da 'Bushido' felsefesinin sertleşmesine ve klanlar arası dayanışmanın (merkezi hükümetin zayıflamasına rağmen) kültürel olarak artmasına neden olmuştur. Arkeolojik olarak Moğol gemilerinde bulunan barutlu bombalar, o dönemdeki teknolojik uçurumu kanıtlamaktadır.",
    "accuracyNote": "Oyunun görsel tarzı 13. yüzyıl yerine 16. yüzyıl samuray estetiğini (katana kullanımı dahil) temel alır. 1274'te samurayların ana silahı tachi ve uzun yay idi. Ancak Moğol kuşatma silahları ve savaş taktikleri tarihsel verilere uygundur.",
    "whyInteresting": "Moğolların kullandığı 'barutlu bombalar', Japonya'da ateşli silahların ilk kez görülmesine neden olmuştur. Ancak Japonlar bu teknolojiyi benimsemek yerine, geleneksel silahlarını kutsallaştırmayı tercih etmişlerdir."
  },
  "chernobyl-disaster": {
    "realHistory": "26 Nisan 1986'da Çernobil Nükleer Santrali'nin 4. reaktöründe yaşanan felaket, sadece bir mühendislik hatası değil, Sovyetler Birliği'nin siyasi ve toplumsal yapısının çöküş belgesidir. Patlama, bir güvenlik testi sırasında reaktörün kontrolsüz bir güç artışıyla termal bir patlamaya uğraması sonucu gerçekleşti. Sovyet yönetiminin 'hata kabul etmez' yapısı ve gizlilik saplantısı, felaketin ilk günlerinde dünyanın (ve hatta bölge halkının) uyarılmasını engellemiş, bu da Pripyat şehrindeki binlerce insanın ölümcül dozda radyasyona maruz kalmasına yol açmıştır.\n\nFelaketle mücadele eden 'Likidatörler' (itfaiyeciler, madenciler ve askerler), o dönemde radyasyonun etkilerini tam bilmeden veya bile bile kendilerini feda etmişlerdir. Reaktörün içine düşen helikopterler, çatılardaki grafit parçalarını elleriyle atan 'biyo-robotlar' ve reaktörün altına tünel kazan madenciler, tarihin gördüğü en büyük fedakarlık öykülerinden biridir. Çernobil, Sovyetlerin 'teknolojik üstünlük' iddiasını yerle bir etmiş ve Gorbaçov'un Glasnost (Açıklık) politikasını kaçınılmaz kılmıştır. Patlamanın yarattığı radyoaktif bulutlar Avrupa'nın içlerine kadar ulaşmış, nükleer enerjinin riskleri konusunda küresel bir paradigma değişimi yaratmıştır. Bugün Çernobil, insanların terk ettiği ama doğanın vahşi bir şekilde geri döndüğü, zamanın durduğu devasa bir anıt mezar niteliğindedir.",
    "accuracyNote": "HBO dizisi Chernobyl, kontrol odasındaki diyaloglardan reaktörün teknik çalışma prensibine kadar muazzam bir araştırma ürünüdür. Radyasyon yanıklarının aşamalı tasviri ve Sovyet bürokrasisinin işleyişi tarihsel gerçeklerle %95 oranında örtüşür.",
    "whyInteresting": "Patlamanın ardından reaktörün altında oluşan ve 'Fil Ayağı' (Elephant's Foot) adı verilen erimiş yakıt kütlesi, o kadar radyoaktifti ki, yanındaki bir insanı 300 saniye içinde öldürebilirdi."
  },
  "oppenheimer-trinity": {
    "realHistory": "1942 yılında başlayan Manhattan Projesi, insanlık tarihinin en büyük askeri-bilimsel organizasyonudur. J. Robert Oppenheimer'ın bilimsel liderliğinde, New Mexico çöllerindeki gizli Los Alamos Laboratuvarı'nda yürütülen çalışmalar, maddenin en derin sırlarını bir silaha dönüştürmeyi amaçlamıştır. Bu proje, sadece bir bomba yapmak değil, aynı zamanda müttefiklerin Nazi Almanyası'ndan önce bu güce ulaşma yarışıdır. 16 Temmuz 1945'teki 'Trinity' testi, dünyanın ilk nükleer patlaması olarak tarihe geçmiş ve Oppenheimer'ın 'Ben şimdi ölüm oldum' itirafıyla bilimin masumiyetini kaybettiği an olarak simgeleşmiştir.\n\nProje, bütçesi, lojistik ağı ve içindeki dehaların (Enrico Fermi, Richard Feynman, Niels Bohr) sayısı bakımından eşsizdir. Ancak bombanın Hiroşima ve Nagazaki'de kullanılmasının ardından yaşanan etik tartışmalar, Oppenheimer'ı bir 'ulusal kahraman'dan 'güvenlik tehdidi'ne dönüştüren siyasi bir sürece yol açmıştır. Soğuk Savaş'ın başlangıcında, Oppenheimer'ın nükleer silahlanma yarışına karşı duruşu, Lewis Strauss gibi figürlerin onu 'komünist sempatizanı' olarak yaftalamasına neden olan 1954'teki meşhur güvenlik duruşmasıyla sonuçlanmıştır. Bu olay, bilimin siyaset ve ideolojiyle olan tehlikeli ilişkisinin en trajik örneğidir.",
    "accuracyNote": "Christopher Nolan'ın filmi, hem teknik süreçleri hem de 1954 duruşmasını kelimesi kelimesine gerçek tutanaklara dayanarak aktarır. Oppenheimer'ın iç dünyasındaki parçalanma ve bilimsel topluluktaki gerilimler tarihsel biyografilerle tam uyumludur.",
    "whyInteresting": "Los Alamos'ta çalışan bilim insanları, bombanın patlamasıyla atmosferin tutuşup tüm dünyayı yakma ihtimalini (çok düşük de olsa) hesaplamışlar ve testi bu risk altında gerçekleştirmişlerdir."
  },
  "gladiator-colosseum": {
    "realHistory": "M.S. 80 yılında açılan Flavian Amfitiyatrosu (Kolezyum), Roma İmparatorluğu'nun mühendislik zekasının ve toplumsal kontrol mekanizmasının zirvesidir. İmparator Vespasian tarafından bir zamanlar Neron'un özel gölünün bulunduğu yere inşa edilen bu devasa yapı, 'halka ait bir eğlence alanı' mesajı taşıyordu. Kolezyum'da düzenlenen oyunlar, sadece gladyatör dövüşlerinden ibaret değildi; Roma'nın fethettiği uzak topraklardan getirilen egzotik hayvanların sergilendiği 'Venatio'lar, tarihi savaşların yeniden canlandırıldığı devasa prodüksiyonlar ve hatta arenanın suyla doldurulup gemi savaşlarının yapıldığı 'Naumachia'lar düzenlenirdi.\n\nKolezyum'un altındaki 'Hypogeum' adı verilen tünel ve asansör sistemleri, gösterilerin dramatik etkisini artırmak için tasarlanmış bir antik özel efekt merkezidir. Gladyatörler, sanılanın aksine her dövüşte ölmeyen, yüksek maliyetli ve popüler 'spor yıldızları' gibiydiler; ancak mütteki (infamis) statüsündeydiler. Roma halkı için Kolezyum, imparatorla doğrudan temas kurabildikleri, taleplerini haykırabildikleri ve Roma'nın 'dünya hakimi' olduğu hissini tattıkları bir ritüel alanıydı. 'Ekmek ve Oyunlar' politikası, Kolezyum'un bu devasa gölgesinde işsiz kitleleri meşgul tutarak imparatorluğun ömrünü yüzyıllarca uzatmıştır.",
    "accuracyNote": "Gladiator filmi, atmosferik olarak başarılı olsa da, Commodus'un karakteri ve ölümü konusunda kurgusaldır. Gerçek Commodus, arenada savaşmayı çok sevmiş olsa da, suikast sonucu banyosunda bir güreşçi tarafından boğularak öldürülmüştür.",
    "whyInteresting": "Kolezyum'un tepesinde bulunan ve 'Velarium' adı verilen devasa tente sistemi, seyircileri güneşten korumak için tasarlanmıştı ve bu karmaşık sistemi sadece uzman Romalı denizciler kontrol edebilirdi."
  },
  "the-crown-monarchy": {
    "realHistory": "Kraliçe II. Elizabeth'in 1952'de tahta çıkışı, Britanya İmparatorluğu'nun çözüldüğü ve yerini Commonwealth'e (İngiliz Milletler Topluluğu) bıraktığı devasa bir jeopolitik dönüşüme denk gelir. Modern Britanya monarşisi, 1688'deki Görkemli Devrim'den bu yana 'Anayasal Monarşi' prensibiyle yönetilir. Bu sistemde hükümdar, 'hüküm sürer ama yönetmez' (reigns but does not rule). Yani Kraliçe'nin siyasi bir otoritesi yoktur; ancak Parlamento ve Başbakan üzerinde 'danışılma, teşvik etme ve uyarma' hakkı gibi sembolik ama etkili bir güce sahiptir.\n\nNetflix'in The Crown dizisi, monarşinin bu sembolik yapısının 'kurumsal bir hayatta kalma' mücadelesine nasıl dönüştüğünü anlatır. Kraliçe, 70 yıllık hükümdarlığı boyunca Winston Churchill'den Margaret Thatcher'a kadar 15 başbakanla çalışmış ve her hafta onlarla 'Gizli Görüşme' yapmıştır. Bu görüşmelerin içeriği hiçbir zaman açıklanmaz, ancak monarşinin devlet işleyişindeki sürekliliğini temsil eder. Tarihsel olarak II. Elizabeth, monarşinin 'eskimeye yüz tutmuş bir kurum' olarak görülmesini engelleyerek, onu İngiliz kimliğinin ve ulusal birliğinin değişmez bir sembolü haline getirmeyi başarmıştır. Bu süreçte ailevi krizler, skandallar ve toplumsal değişimlere karşı verilen tepkiler, monarşinin hem esnekliğini hem de katı geleneklerine olan bağlılığını test etmiştir.",
    "accuracyNote": "Dizi, tarihi olayların kronolojisini ve saray protokollerini büyük oranda doğru yansıtır; ancak diyaloglar ve aile fertlerinin psikolojik durumları tamamen kurgusaldır. Saray buraları 'hayal ürünü drama' olarak nitelendirmiştir.",
    "whyInteresting": "Kraliçe II. Elizabeth, İngiltere'deki tüm pasaportların ve sürücü belgelerinin teknik sahibi olduğu için, kendisinin pasaportu veya ehliyeti yoktu. Ayrıca 'Vatanın Anası' rolüyle, siyasi çatışmaların üzerinde bir hakem gibi görülürdü."
  }
};

let cards = JSON.parse(fs.readFileSync(path, 'utf8'));
let count = 0;

cards = cards.map(card => {
  if (enrichmentData[card.id]) {
    count++;
    return { ...card, ...enrichmentData[card.id] };
  }
  return card;
});

fs.writeFileSync(path, JSON.stringify(cards, null, 2), 'utf8');
console.log(`Enriched ${count} flagship cards successfully.`);
